### ISSUE TITLE
Can not start this APP

### ISSUE THREAD

**Issue by KimmySicling** [llens/CryptoCurrencyTrader#12]
Linux python 2.7: these modules should be installed
 237  pip install pytrends
  239  pip install blockchain
  242  pip install praw
  244  pip install scrapy
  256  pip install bs4
  261  pip install nltk
  263  pip install twython

Linux 3.6:
UnsatisfiableError: The following specifications were found to be in conflict:
  - multiprocessing -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

Windows 2.7:
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7*
  - tensorflow -> html5lib ==0.9999999
  - tensorflow -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by llens** [comment]
I am unsure what the output given here is from. Can you tell me what operating system and which version of python you are using? Also what command you ran to get this above?

**Comment by llens** [comment]
I suspect the problem here is that you are trying to install a Python 2.7 library to a Python 3.6 environment. You need to make sure you are installing all the libraries from Python 2.7 sources, the code does not work with Python 3.6.

**Comment by KimmySicling** [comment]
Thanks llens,

The information i paste is when i select anaconda, so i follow your instruction to install miniconda, but  get this alert:

(tensorflow-p2) @winner:~/miniconda$ conda install -c auto multiprocessing statsmodels arch
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - arch

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/auto/linux-64
  - https://conda.anaconda.org/auto/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

So i search and install one by one
**conda install -c auto multiprocessing
conda install -c conda-forge statsmodels
conda install -c bashtage arch**

(tensorflow-p2) @:~/CryptoCurrencyTrader$ python data_input_processing.py
Traceback (most recent call last):
  File "data_input_processing.py", line 8, in <module>
    from non_price_data import google_trends_interest_over_time, initialise_google_session, hash_rate
  File "/home/CryptoCurrencyTrader/non_price_data.py", line 4, in <module>
    from pytrends.request import TrendReq
ImportError: No module named **pytrends.request**

So i install packages needed for scripts in app

**237 pip install pytrends
239 pip install blockchain
242 pip install praw
244 pip install scrapy
256 pip install bs4
261 pip install nltk
263 pip install twython**

when go to run "python sklearn_evaluation_script.py"
got this:
 from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

I got solution from : https://github.com/ContinuumIO/docker-images/issues/49
**sudo apt install libgl1-mesa-glx**

finally i think i solve all warning.

And i suggest add some start commands for newbie showing the sequence of the scripts.

Thanks.

**Comment by KimmySicling** [comment]
pip install pytrends blockchain praw scrapy bs4 nltk twython
-- in a single line
