### ISSUE TITLE
could twitter data improve sentiment analysis?

### ISSUE THREAD

**Issue by zeuleo** [llens/CryptoCurrencyTrader#15]
I have some twitter data streamed over the last months regarding cryptocurrencies. Do you think this could enrich sentiment analysis?

**Comment by llens** [comment]
It could well be useful, I am focussing on getting the ml algorithm to perform about as well as the simple momentum strategy (added for comparison) on quantitative before re-adding the non-price data. I am trying to be a bit more systematic than before. I am always happy to collaborate
