### ISSUE TITLE
problem with "pip install arch polyaxon"

### ISSUE THREAD

**Issue by pranav-manik** [llens/CryptoCurrencyTrader#16]
Im having a problem installing arch
Im getting this

(tensorflow-p2) user@user-VirtualBox:~$ pip install arch polyaxon
Collecting arch
  Using cached arch-4.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6l2Yyi/arch/setup.py", line 13, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6l2Yyi/arch/

specifically "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6l2Yyi/arch/" is my issue

**Comment by llens** [comment]
It looks like you needs to install cython. pip install cython.
