### ISSUE TITLE
 KeyError: 'test_strategy_score'

### ISSUE THREAD

**Issue by Gudui** [llens/CryptoCurrencyTrader#19]
First of all, it's a very interesting concept you're developing, however when running sklearn_evaluation_script.py I'm receiving the following error;

  File "/home/gudui/CryptoCurrencyTrader/strategy_evaluation.py", line 135, in post_process_training_results
    fitting_dictionary['test_strategy_score'],
KeyError: 'test_strategy_score'

I'm using default values for the strategy dict except i've changed it to work on BTC_USDT, as i don't call data for XMR_DASH.

It seems that the key is never created at all, which i think it should be in trading_strategy_fitting.py, in
    if strategy_dictionary['regression_mode'] == 'regression':
        fitting_dictionary = {
            'training_strategy_score': training_strategy_score,
            'fitted_strategy_score': fitted_strategy_score,
            'validation_strategy_score':validation_strategy_score,
            'train_indices': train_indices,
            'test_indices': test_indices,
            'validation_indices': validation_indices,
'error': error}

Edit, my best guess is that it should be replaced with fitted_strategy_score
Thanks in advance.

**Comment by llens** [comment]
Hopefully, that last push has it working for you. I had changed the naming of the train, test, val vars to match convention, and not pushed the new version of the second file. Let me know if there are still issues.

**Comment by Gudui** [comment]
Still an issue with executing it, it seems that it cannot import the post processing method now,

gudui@buddy:~/CryptoCurrencyTrader$ python sklearn_evaluation_script.py
/home/gudui/.local/lib/python2.7/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "
Traceback (most recent call last):
  File "sklearn_evaluation_script.py", line 3, in <module>
    from trading_strategy_fitting import fit_strategy, offset_scan_validation, tic, underlined_output, import_data,\
  File "/home/gudui/CryptoCurrencyTrader/trading_strategy_fitting.py", line 4, in <module>
    from strategy_evaluation import post_process_training_results, output_strategy_results
  File "/home/gudui/CryptoCurrencyTrader/strategy_evaluation.py", line 3, in <module>
    from strategy_evaluation import post_process_training_results, output_strategy_results
ImportError: cannot import name post_process_training_results

**Comment by Gudui** [comment]
@llens

**Comment by llens** [comment]
I'lll have a look at that.

**Comment by Gudui** [comment]
@llens Hmm, did you accidentally deleted it ? I cannot find it

**Comment by llens** [comment]
I think you just need to run pip install twython, for nltk to work.
I am planning an overhaul of the project, so there should hopefully be a more streamlined and effective project soon, with fewer dependencies.

**Comment by Gudui** [comment]
@llens No, i'm receving the same error. You're importing a method signature which hasen't been declared.

If i revert to your previous commit and replace test_strategy_score with fitted_strategy_score in the strategy_evaluation.py, it works as it should.

Sounds interesting with an overhaul of the project. If you need any help, I'll gladly contribute.

**Comment by Gudui** [comment]
@llens I would not see this as resolved. If anyone else clone it, the repository will not compile in its current sate.

**Comment by llens** [comment]
I would recommend using the previous commit for now. As the current f

**Comment by llens** [comment]
I have reopened it. The current commit will be replaced entirely in the near future. I would be happy for the help, I think once I get a minimum working example of the overhaul out, which shouldn't be too long hopefully (it will try to do a lot less in terms of functionality but on a more solid theoretical base), we will have a good code base to coordinate future work on top of.

**Comment by Gudui** [comment]
@llens Sounds fine by me. Is it ok, if report any errors I occur when working with the project?

**Comment by llens** [comment]
Please continue to catalogue them, in case we use anything from the original code base, if you were to fix them I would definitely accept the pull request. 

To give  you some context a lot of the errors crop up as a result of the codebase having a lot more features than it needs to in order to address the problem at hand, and also I need to write tighter code and manage complexity better in a lot of places, which is why I decided on the overhaul rather than patching an imperfect project. The project developed organically and I enhanced it and tried new things, which meant I didn't really have a big picture design in mind and it grew inelegantly in a lot of ways.
