### ISSUE TITLE
profit_fraction is tuple, not int

### ISSUE THREAD

**Issue by Gudui** [llens/CryptoCurrencyTrader#21]
When executing tensorflow_fitting_script.py im receving the following error, where it expect an int, but gets a tuple of two profit fractions, should both just be added then?

Traceback (most recent call last):
  File "tensorflow_fitting_script.py", line 89, in <module>
    tensorflow_offset_scan_validation(strategy_dictionary, data_to_predict, fitting_inputs, fitting_targets, offsets)
  File "/home/gudui/CryptoCurrencyTrader/trading_strategy_fitting.py", line 185, in tensorflow_offset_scan_validation
    total_profit += profit_fraction
TypeError: unsupported operand type(s) for +=: 'int' and 'tuple'

**Comment by llens** [comment]
You should just ignore the second entry in the tuple, it is the profit from the validation step and it is not needed for the tensorflow script as it stands as it does not have a further fitting step, e.g. time step fitting.
