### ISSUE TITLE
Clarification of the strategy_dictionary

### ISSUE THREAD

**Issue by Gudui** [llens/CryptoCurrencyTrader#22]
I'm trying to understand some of the different variables in the strategy_dictionary which doesn't seem to be used, yet.

"ticker_2"
"scraper_current_2
"filename_2"

My best interpretation of the code i that they should've been used to support multiple coins while fitting. What are you trying to accomplish? Was it to learn when to sell and by between two currencies?

**Comment by llens** [comment]
At an early stage the project would pull and fit using two price series, I removed this and plan to replace it with multiple time series and portfolio management in future.
