### ISSUE TITLE
fitting_inputs are not taking sentiments into account, uncommented code

### ISSUE THREAD

**Issue by Gudui** [llens/CryptoCurrencyTrader#25]
It seems that generate_training_variables() in data_input_processing.py don't take the retrieved sentiment analysis into account, why is that?

    fitting_inputs = np.vstack((
        data_obj.momentum,
        data_obj.exponential_moving_volatility_1,
        data_obj.hidden_markov,
        #data_obj.kalman_signal,
        # data_obj.close[:-1],
        #data_obj.open[:-2],
        # data_obj.high[:-1],
        # data_obj.low[:-1],
        # pad_nan(data_obj.close[:-2], 1),
        # pad_nan(data_obj.open[:-2], 1),
        # pad_nan(data_obj.high[:-2], 1),
        # pad_nan(data_obj.low[:-2], 1),
        # pad_nan(data_obj.close[:-3], 2),
        # pad_nan(data_obj.open[:-3], 2),
        # pad_nan(data_obj.high[:-3], 2),
        # pad_nan(data_obj.low[:-3], 2),
        #data_obj.google_trend_score[:-1].T,
        #data_obj.web_sentiment_score[:-1],
        #data_obj.hash_rates[:-1]
))

**Comment by Gudui** [comment]
Ahh, ok, i get it, it's because the non_price_data isn't enabled at the moment.

**Comment by llens** [comment]
For testing, I would often fit on smaller subsets of data, it can take much longer to fit with more variables. 

For instance, I often see if the fitting performs better or worse than a simple momentum strategy, given the same inputs. The control over this element is one thing I hope to address in the v2.
