### ISSUE TITLE
Meaning of Offset in Strategy_dict

### ISSUE THREAD

**Issue by Gudui** [llens/CryptoCurrencyTrader#27]
I'm not quite sure what the offset contribute to? You're specifing the end_time by using the offset, but the actual usage of this is not clear for me.

Thanks in advance.

**Comment by llens** [comment]
The offset is a validation test to test for overfitting. Any strategy which fits the initial data profitably should also work at an arbitrary offset time. If not has overfitted the training data, and the strategy would not be effective on live trading data.
