### ISSUE TITLE
enhancement - investigate adding candlestick patterns 

### ISSUE THREAD

**Issue by johndpope** [llens/CryptoCurrencyTrader#4]
@npapapietro has done some ground work here - 

I wonder if this code / logic  has any place here 
https://github.com/npapapietro/CandleStickPatterns/blob/master/candlestickpatterns.py

I also found this code from  @GYDSB https://github.com/johndpope/candlestickChart/blob/master/Candlestick.py

**Comment by llens** [comment]
I think the idea of candlestick patterns is overcomplicating the input, as any candlestick pattern would simply be a derivative open, high, low, close
I can achieve a much more versatile input method by allowing simply open, high, low, close as inputs at various offsets, (a three candle candlestick pattern is specified entirely by the OHLC at the last three timessteps for instance ) this would capture candlestick patterns as inputs generally while allowing for a wider range of possibilities.

I am happy to provide support for the candlestick patterns in this general form and will get to work on it.

**Comment by llens** [comment]
Pushed version with potential for OHLC candles at offsets as inputs, this should allow for the input of candlestick patterns, as well as more general OHLC candle inputs.

**Comment by johndpope** [comment]
nice work. will check it out.
