### ISSUE TITLE
No conda 'multiprocessing' package found

### ISSUE THREAD

**Issue by imkane** [llens/CryptoCurrencyTrader#5]
Thanks for this project, it looks awesome!

Trying to install on CentOS 7:

```
$ conda install -c auto multiprocessing statsmodels arch
Fetching package metadata: ...Could not connect to https://conda.binstar.org/auto/linux-64/
Error: No packages found in current linux-64 channels matching: multiprocessing
You can search for this package on Binstar with
    binstar search -t conda multiprocessing
You may need to install the Binstar command line client with
    conda install binstar
```
Any ideas?

**Comment by imkane** [comment]
I followed https://www.atlantic.net/community/howto/install-python-2-7-centos-anaconda/ to get a bit further, but now:

```
(tensorflow-p2)[user ~]$ conda install -c auto multiprocessing statsmodels arch
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current linux-64 channels:
  - arch
Did you mean one of these?
    archie, mach, darc
You can search for this package on anaconda.org with
    anaconda search -t conda arch
```

**Comment by llens** [comment]
Hi,
     unless I have made a mistake and not removed it, the current version of the script does not require arch to be installed (I don't think there is a conda version of arch available.)

**Comment by llens** [comment]
Try instead conda install -c auto multiprocessing statsmodels and see if the script works. Please reopen the issue if it does not.

**Comment by imkane** [comment]
Thanks! I removed "arch" and it worked :)
