### ISSUE TITLE
How to actually run it?

### ISSUE THREAD

**Issue by imkane** [llens/CryptoCurrencyTrader#6]
I followed the install instructions, but not sure how to run it? My apologies as I'm new to Python :( But I'd love to be more involved and share any enhancements I come up with.

**Comment by llens** [comment]
You should simply be able to run either sklearn_evaluation_script.py or tensorflow_fitting_script.py the settings which control the behaviour of these scripts are found in the strategy_dictionary within each, with each setting explained in the README. Let me know if you need any further information.

**Comment by dddanmar** [comment]
Just a few items I wanted to note after I did a fresh clone on a new machine:

- Ensure when you clone to use recursive to get all code `git clone --recursive https://github.com/llens/CryptoCurrencyTrader.git`
- Install requirements `pip install -r requirements.txt`
- Ensure your tensorflow version is 1.2.0. A dependency, PolyAxon, does not work with the latest TensorFlow 1.3.0 `pip install tensorflow-gpu==1.2.0`
- Install `blockchain` `pip install blockchain` 
- Create a new Reddit app at https://www.reddit.com/prefs/apps
- Create an API_settings.py file with `poloniex_API_secret`, `poloniex_API_key`, `google_username`, `google_password`, `client_id`, `client_secret`, `user_agent` (`client_id`, `client_secret` and `user_agent` are from reddit)
- Create an __init__.py in the Web Scraping/Sentiment folder so the import works in `sklearn_evaluation_script.py` `touch CryptocurrencyWebScrapingAndSentimentAnalysis/__init__.py`

@llens If I make a pull request or two to fix the above items will they be accepted with code/sample settings/documentation?

**Comment by llens** [comment]
Yes, I would be happy to accept these changes.

**Comment by dddanmar** [comment]
I've realised the last point is not valid - I cloned the CryptocurrencyWebScrapingAndSentimentAnalysis repo and saw you have already created an __init__.py file there but not merged it with this repository.

**Comment by llens** [comment]
Merged 
__init__.py

**Comment by maithanhtan** [comment]
Hi,
I try to run the script as instruction but get the eror: pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.
I had turn my google allow let secure app to on but still this error. Can you help me?
Thanks
Here is the detail:
~/CryptoCurrencyTrader# python ./tensorflow_fitting_script.py
Traceback (most recent call last):
  File "./tensorflow_fitting_script.py", line 97, in <module>
    strategy_dictionary, search_iterations)
  File "./tensorflow_fitting_script.py", line 13, in random_search
    data_local, data_2, strategy_dictionary)
  File "/root/CryptoCurrencyTrader/trading_strategy_fitting.py", line 46, in input_processing
    data_to_predict_local, strategy_dictionary)
  File "/root/CryptoCurrencyTrader/data_input_processing.py", line 327, in generate_training_variables
    data_obj.calculate_indicators(strategy_dictionary, prior_data_obj=prior_data_obj)
  File "/root/CryptoCurrencyTrader/data_input_processing.py", line 165, in calculate_indicators
    self.non_price_data(strategy_dictionary, prior_data_obj=prior_data_obj)
  File "/root/CryptoCurrencyTrader/data_input_processing.py", line 169, in non_price_data
    self.google_trend_data(strategy_dictionary)
  File "/root/CryptoCurrencyTrader/data_input_processing.py", line 187, in google_trend_data
    dates, interest = google_trends_interest_over_time(pytrend, [search_term, ])
  File "/root/CryptoCurrencyTrader/non_price_data.py", line 14, in google_trends_interest_over_time
    pytrend_local.build_payload(kw_list=search_terms)
  File "/root/anaconda2/lib/python2.7/site-packages/pytrends/request.py", line 107, in build_payload
    self._tokens()
  File "/root/anaconda2/lib/python2.7/site-packages/pytrends/request.py", line 118, in _tokens
    trim_chars=4,
  File "/root/anaconda2/lib/python2.7/site-packages/pytrends/request.py", line 87, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.

**Comment by llens** [comment]
Can you confirm that you followed the following step?

Setup

To run as a standalone script add a file named API_settings.py containing your poloniex API, google and reddit API login: poloniex_API_key = ""
poloniex_API_secret = ""
google_username = ""
google_password = ""
client_id = ""
client_secret = ""
user_agent = 'Python Scraping App'

**Comment by maithanhtan** [comment]
Yes, I had follow this and made the api settings file on the same folder of CryptoCurrencyTrader.
Is there anyway i can debug the pytrends function scrape google search?

**Comment by dddanmar** [comment]
I think there might be an upstream bug with https://github.com/GeneralMills/pytrends/issues/169

**Comment by llens** [comment]
Hi, I have pushed a version that is working with version 4.2.2 of pytrends can you retry it with this version of the script.

Also you could run https://github.com/GeneralMills/pytrends/blob/master/examples/example.py separately to confirm that pytrends is working independently.

**Comment by maithanhtan** [comment]
Thanks, It work now
