### ISSUE TITLE
Disable non price data and read time range from poloniex

### ISSUE THREAD

**Issue by sabotage3d** [llens/CryptoCurrencyTrader#9]
Hi,
Is it currently possible to disable non price data? I am trying to read a small price range from Poloniex and predict non trained range for testing. I am playing with the dictionary below, but I always get stuck on tensor-flow forever.

```
    strategy_dictionary = {
        'trading_currencies': ['USDT', 'BTC'],
        'ticker_1': 'USDT_BTC',
        #'scraper_currency_1': 'BTC',
        'candle_size': 1800,
        'n_days': 1,
        'offset': 0,
        'bid_ask_spread': 0.004,
        'transaction_fee': 0.0025,
        'train_test_validation_ratios': [0.5, 0.25, 0.25],
        'output_flag': True,
        'plot_flag': False,
        'target_score': 'idealstrategy',
        'windows': [10, 50, 100],
        'regression_mode': 'regression',
        'preprocessing': 'None',
        'ml_mode': 'tensorflow',
        'sequence_flag': False,
        'output_units': 1,
        'web_flag': True,
        #'filename1': "USDT_BTC.csv",
        #'scraper_page_limit': 10,
    }
```

**Comment by llens** [comment]
Hi,
    it can take a long time to fit when it isn't running on a GPU, I am planning to implement a less resource intensive fitting when I have time. In the meantime to remove non-price data, you can comment out the bottom three lines from the vstack on lines 329 of data input processing. To speed up further you could so comment out one of the ema, emv and/or the Kalman filter.]

    fitting_inputs = np.vstack((
        data_obj.exponential_moving_average_1,
        data_obj.exponential_moving_average_2,
        data_obj.exponential_moving_average_3,
        data_obj.exponential_moving_volatility_1,
        data_obj.exponential_moving_volatility_2,
        data_obj.exponential_moving_volatility_3,
        data_obj.exponential_moving_volume_1,
        data_obj.exponential_moving_volume_2,
        data_obj.exponential_moving_volume_3,
        data_obj.kalman_signal,
        # data_obj.close[:-1],
        data_obj.open[:-2],
        # data_obj.high[:-1],
        # data_obj.low[:-1],
        # pad_nan(data_obj.close[:-2], 1),
        # pad_nan(data_obj.open[:-2], 1),
        # pad_nan(data_obj.high[:-2], 1),
        # pad_nan(data_obj.low[:-2], 1),
        # pad_nan(data_obj.close[:-3], 2),
        # pad_nan(data_obj.open[:-3], 2),
        # pad_nan(data_obj.high[:-3], 2),
        # pad_nan(data_obj.low[:-3], 2),
        data_obj.google_trend_score[:-1].T,
        data_obj.web_sentiment_score[:-1],
        data_obj.hash_rates[:-1]
        ))

**Comment by sabotage3d** [comment]
Thanks,
Can I actually pull historical data from poloniex? Do I need the csv files as the csv data is huge. For testing I just want to pull a few days historical data and predict a few hours ahead.

**Comment by llens** [comment]
If web flag is set to true, it is pulling data from poloniex and the csv is not required.

**Comment by sabotage3d** [comment]
Just to check if I got it right `n_days` would give me previous days starting from the current time and `candle_size` is in seconds for 1800 this would be 30 minutes. This would be the historical data to train the model and `windows` would give me prediction for future periods, is it in days or I can use different time units?

**Comment by llens** [comment]
Yes n_days gives the historical data n_days into the past starting from the current time unless an offset value is set. Windows are the window sizes and are in units of the candlestick size, so window 3 for 30 min candles is 90 min windows.

**Comment by sabotage3d** [comment]
After commenting the lines from data input processing it still scrapping the web pages. Do I need to remove it from the function retrieve_data as well?

**Comment by llens** [comment]
This actually a rookie error on my part, you need to specify a folder that exists on your system in line 165 of trading_strategy_fitting.py. Change /home/thomas/test to /tmp/test. I will change this in the main repo.

fitting_dictionary, error = tensorflow_sequence_fitting(
--
165 | '/home/thomas/test', train_indices, test_indices, validation_indices, fitting_inputs, fitting_targets,
